import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { DialogueDslGeneratedModule, DialogueDslGeneratedSharedModule } from './generated/module.js';
import { DialogueDslValidator, registerValidationChecks } from './dialogue-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type DialogueDslAddedServices = {
    validation: {
        DialogueDslValidator: DialogueDslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type DialogueDslServices = LangiumServices & DialogueDslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const DialogueDslModule: Module<DialogueDslServices, PartialLangiumServices & DialogueDslAddedServices> = {
    validation: {
        DialogueDslValidator: () => new DialogueDslValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createDialogueDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    DialogueDsl: DialogueDslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        DialogueDslGeneratedSharedModule
    );
    const DialogueDsl = inject(
        createDefaultModule({ shared }),
        DialogueDslGeneratedModule,
        DialogueDslModule
    );
    shared.ServiceRegistry.register(DialogueDsl);
    registerValidationChecks(DialogueDsl);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, DialogueDsl };
}
